_target_: src.models.lrw_module.LRWLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.cnn_gru.CnnGRUModel
  gru_hidden: 1024
  gru_layers: 3
  n_classes: 500
  use_border: false
  dropout: 0.5

label_smooth: false
use_boundary: false
use_mixup: false